---
version: ~> 1.0
import: agoloncser/travis-shared-configs:docker-ansible-matrix.yml
env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}
    - FROM_DISTRO=ubuntu
  jobs:
    - IMAGE=docker-ansible-ubuntu2010 FROM_TAG=20.10
    - IMAGE=docker-ansible-ubuntu2004 FROM_TAG=20.04
    - IMAGE=docker-ansible-ubuntu1804 FROM_TAG=18.04
    - IMAGE=docker-ansible-ubuntu1604 FROM_TAG=16.04
