---
name: Molecule testing
on:
  push: {}
  pull_request: {}
  schedule:
    - cron: "12 6 * * 3"

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE: docker-ansible-ubuntu2104
            FROM_TAG: "21.04"
          - IMAGE: docker-ansible-ubuntu2010
            FROM_TAG: "20.10"
          - IMAGE: docker-ansible-ubuntu2004
            FROM_TAG: "20.04"
          - IMAGE: docker-ansible-ubuntu1804
            FROM_TAG: "18.04"

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.IMAGE }}:latest
          build-args: |
            FROM_TAG=${{ matrix.FROM_TAG }}
