---
name: Molecule testing
on:
  push: {}
  pull_request: {}
  schedule:
    - cron: "12 6 * * *"

jobs:
  molecule:
    env:
      FROM_DISTRO: ubuntu
      VERSION: 3
    runs-on: ubuntu-latest
    # continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      # experimental: [false]
      matrix:
        include:
          - IMAGE: docker-ansible-ubuntu2010
            FROM_TAG: 20.10
            # experimental: true
          - IMAGE: docker-ansible-ubuntu2004
            FROM_TAG: 20.04
          - IMAGE: docker-ansible-ubuntu1804
            FROM_TAG: 18.04

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.IMAGE }}:latest

          # build-args: |
          #   arg1=value1
          #   arg2=value2

  # galaxy_upload:
  #   runs-on: ubuntu-latest
  #   needs: molecule
  #   steps:
  #     - name: Import to Galaxy
  #       uses: robertdebock/galaxy-action@1.0.3
  #       with:
  #         galaxy_api_key: ${{ secrets.galaxy_api_key }}
